### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by phpdave11** [openvenues/php-postal#1]
I followed the installation instructions, and I was able to compile libpostal and the php extension on Ubuntu 15.10.

However, now every PHP command is very slow -- there's about a 4 second delay with postal.so enabled.

postal.so disabled:

```
$ time php -v
PHP 5.6.11-1ubuntu3.3 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
real    0m0.049s
user    0m0.016s
sys 0m0.016s
```

postal.so enabled:

```
$ time php -v
PHP 5.6.11-1ubuntu3.3 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
real    0m3.809s
user    0m0.756s
sys 0m1.784s
```

**Comment by thatdatabaseguy** [comment]
It seems like what you're talking about is startup cost, not overall performance. There is a one-time cost at import/startup time for loading libpostal, mainly because it needs to read the 2G of machine learning models (parser, language classifier) from disk into memory before it can be used. These are mostly sequential reads, and the filesystem cache often helps, as do SSDs when that's an option e.g. in AWS.

Calls to libpostal (parse_address, expand_address) take a few tens of microseconds from most of the bindings. If there's a legitimate performance problem there in PHP, I'll look into it, but there's not much I can do about the startup cost at the moment. It requires making the models significantly smaller, which might affect accuracy, which I'm currently trying to improve not decrease.

**Comment by phpdave11** [comment]
Thanks!  That makes complete sense.  I will try to find a way to have libpostal always running in memory, and then possibly build an API so that I can parse an address quickly.  Awesome work, by the way.  I am truly impressed with the work you've done on this project.

**Comment by thatdatabaseguy** [comment]
Thanks! There's a parser update in the works as well, keep an eye out. I'll update the issue again if we're able to reduce the model size.

**Comment by thatdatabaseguy** [comment]
Closing, libpostal 1.0 is out now, uses slightly less memory (1.8G, subsequent models might use more as the data sets grow). Initial load time still depends on whether it's SSD (hopefully) or a spinning disk.
